<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
	<AddRazorSupportForMvc>true</AddRazorSupportForMvc>  
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CoreCLR-NCalc" Version="3.1.253" />
    <PackageReference Include="Cronos" Version="0.13.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Localization.Abstractions" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Argent.Core\Argent.Core.csproj" />
  </ItemGroup>

</Project>
