namespace Argent.Core.Workers;

/// <summary>
/// The outcome of provisioning a worker or rotating its key. The plaintext key travels with the
/// result rather than being generated by the caller, so the key shown to the administrator is by
/// construction the key that was hashed and stored.
/// </summary>
/// <param name="Worker">The stored worker. Its <see cref="Worker.ApiKeyHash"/> is the hash of <paramref name="ApiKey"/>.</param>
/// <param name="ApiKey">Plaintext, shown once and never persisted.</param>
public record WorkerProvisioningResult(Worker Worker, string ApiKey);
